openapi: 3.0.3
info:
  title: Senzing API draft - OpenAPI 3.0
  description: |-
   This is draft of a Senzing API service.
  termsOfService: http://senzing.com/terms/
  contact:
    email: support@senzing.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: http://localhost:8250
  - url: "{protocol}://{host}:{port}{path}"
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      host:
        default: localhost
      port:
        default: "8250"
      path:
        default: "/"
tags:
  - name: g2config
    description: G2Config description
    externalDocs:
      description: Find out more
      url: http://senzing.com
  - name: g2configmgr
    description: G2ConfigMgr description
    externalDocs:
      description: Find out more
      url: http://senzing.com
  - name: g2diagnostic
    description: G2Diagnostic description
    externalDocs:
      description: Find out more
      url: http://senzing.com
  - name: g2engine
    description: G2Engine description
    externalDocs:
      description: Find out more
      url: http://senzing.com
  - name: g2product
    description: G2Engine description
    externalDocs:
      description: Find out more
      url: http://senzing.com
paths:

  /g2config/add_data_source:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: g2config_add_data_source
      parameters:
        - name: configHandle
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2config/close:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: g2config_close
      parameters:
        - name: configHandle
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation


  /g2config/create:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: g2config_create
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2config/delete_data_source:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: g2config_delete_data_source
      parameters:
        - name: configHandle
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64

      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2config/destroy:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: g2config_destroy
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2config/init:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: g2config_init
      parameters:
        - name: moduleName
          in: query
          description: TODO
          required: true
          schema:
            type: string
        - name: verboseLogging
          in: query
          description: TODO
          schema:
            type: string
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation

  /g2config/list_data_sources:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: g2config_list_data_sources
      parameters:
        - name: configHandle
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2config/load:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: g2config_load
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2config/save:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: g2config_save
      parameters:
        - name: configHandle
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'


components:
  schemas:
    EmptyJsonString:
      type: object
    ExampleJsonString:
      type: object
      properties:
        exampleKey:
          type: string
    SimpleResponse:
      type: object
      properties:
        result:
          type: string

