openapi: 3.0.3
info:
  title: Senzing API draft - OpenAPI 3.0
  description: |-
   This is draft of a Senzing API service.
  termsOfService: http://senzing.com/terms/
  contact:
    email: support@senzing.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
  - url: http://localhost:8250
  - url: "{protocol}://{host}:{port}{path}"
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      host:
        default: localhost
      port:
        default: "8250"
      path:
        default: "/"
tags:
  - name: g2config
    description: G2Config description
    externalDocs:
      description: Find out more
      url: http://senzing.com
  - name: g2configmgr
    description: G2ConfigMgr description
    externalDocs:
      description: Find out more
      url: http://senzing.com
  - name: g2diagnostic
    description: G2Diagnostic description
    externalDocs:
      description: Find out more
      url: http://senzing.com
  - name: g2engine
    description: G2Engine description
    externalDocs:
      description: Find out more
      url: http://senzing.com
  - name: g2product
    description: G2Engine description
    externalDocs:
      description: Find out more
      url: http://senzing.com
paths:

  /g2config/add-data-source:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: postG2configAddDataSource
      parameters:
        - name: configHandle
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2config/close:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: postG2configClose
      parameters:
        - name: configHandle
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation


  /g2config/create:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: postG2configCreate
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2config/delete-data-source:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: postG2configDeleteDataSource
      parameters:
        - name: configHandle
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64

      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2config/destroy:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: postG2configDestroy
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2config/init:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: postG2configInit
      parameters:
        - name: moduleName
          in: query
          description: TODO
          required: true
          schema:
            type: string
        - name: verboseLogging
          in: query
          description: TODO
          schema:
            type: integer
            format: int64
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation

  /g2config/list-data-sources:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: postG2configListDataSources
      parameters:
        - name: configHandle
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2config/load:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: postG2configLoad
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2config/save:
    post:
      tags:
        - g2config
      summary: TODO
      description: TODO
      operationId: postG2configSave
      parameters:
        - name: configHandle
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2configmgr/add-config:
    post:
      tags:
        - g2configmgr
      summary: TODO
      description: TODO
      operationId: postG2configmgrAddConfig
      parameters:
        - name: configComments
          in: query
          description: TODO
          required: true
          schema:
            type: string
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2configmgr/destroy:
    post:
      tags:
        - g2configmgr
      summary: TODO
      description: TODO
      operationId: postG2configmgrDestroy
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2configmgr/get-config:
    post:
      tags:
        - g2configmgr
      summary: TODO
      description: TODO
      operationId: postG2configGetConfig
      parameters:
        - name: configHandle
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2configmgr/get-config-list:
    post:
      tags:
        - g2configmgr
      summary: TODO
      description: TODO
      operationId: postG2configGetConfigList
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2configmgr/get-default-config-id:
    post:
      tags:
        - g2configmgr
      summary: TODO
      description: TODO
      operationId: postG2configGetDefaultConfigID
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2configmgr/init:
    post:
      tags:
        - g2configmgr
      summary: TODO
      description: TODO
      operationId: postG2configmgrInit
      parameters:
        - name: moduleName
          in: query
          description: TODO
          required: true
          schema:
            type: string
        - name: verboseLogging
          in: query
          description: TODO
          schema:
            type: integer
            format: int64
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation

  /g2configmgr/replace-default-config-id:
    post:
      tags:
        - g2configmgr
      summary: TODO
      description: TODO
      operationId: postG2configmgrReplaceDefaultConfigID
      parameters:
        - name: oldConfigID
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64
        - name: newConfigID
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2configmgr/set-default-config-id:
    post:
      tags:
        - g2configmgr
      summary: TODO
      description: TODO
      operationId: postG2configmgrSetDefaultConfigID
      parameters:
        - name: configID
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2diagnostic/check-db-perf:
    post:
      tags:
        - g2diagnostic
      summary: TODO
      description: TODO
      operationId: postG2diagnosticCheckDBPerf
      parameters:
        - name: secondsToRun
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2diagnostic/destroy:
    post:
      tags:
        - g2diagnostic
      summary: TODO
      description: TODO
      operationId: postG2diagnosticDestroy
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2diagnostic/get-available-memory:
    post:
      tags:
        - g2diagnostic
      summary: TODO
      description: TODO
      operationId: postG2diagnosticGetAvailableMemory
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2diagnostic/get-db-info:
    post:
      tags:
        - g2diagnostic
      summary: TODO
      description: TODO
      operationId: postG2diagnosticGetDBInfo
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2diagnostic/get-logical-cores:
    post:
      tags:
        - g2diagnostic
      summary: TODO
      description: TODO
      operationId: postG2diagnosticGetLogicalCores
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2diagnostic/get-physical-cores:
    post:
      tags:
        - g2diagnostic
      summary: TODO
      description: TODO
      operationId: postG2diagnosticGetPhysicalCores
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2diagnostic/get-total-system-memory:
    post:
      tags:
        - g2diagnostic
      summary: TODO
      description: TODO
      operationId: postG2diagnosticGetTotalSystemMemory
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

  /g2diagnostic/init:
    post:
      tags:
        - g2diagnostic
      summary: TODO
      description: TODO
      operationId: postG2diagnosticInit
      parameters:
        - name: moduleName
          in: query
          description: TODO
          required: true
          schema:
            type: string
        - name: verboseLogging
          in: query
          description: TODO
          schema:
            type: integer
            format: int64
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation

  /g2diagnostic/init-with-config-id:
    post:
      tags:
        - g2diagnostic
      summary: TODO
      description: TODO
      operationId: postG2diagnosticInitWithConfigID
      parameters:
        - name: initConfigID
          in: query
          description: TODO
          schema:
            type: integer
            format: int64
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation

  /g2diagnostic/stream-entity-list-by-size:
    post:
      tags:
        - g2diagnostic
      summary: TODO
      description: TODO
      operationId: postG2diagnosticStreamEntityListBySize
      parameters:
        - name: entitySize
          in: query
          description: TODO
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: TODO
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleJsonString'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimpleResponse'

components:
  schemas:
    EmptyJsonString:
      type: object
    ExampleJsonString:
      type: object
      properties:
        exampleKey:
          type: string
    SimpleResponse:
      type: object
      properties:
        result:
          type: string

